sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.6

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "nsa01775@naver.com"
  - git config --global user.name "pathfinder357"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "ZVy8XWk11Qik9pHlw59Hvp1L+wM5rmX75tu640ZGnop4zyfDzIPCH8pg6Q54umiXE+mqw25aP+zectFZHAqJdCSSp1TO0jgzJoo/0ZYhsH+KdQAE5SaF8+VglJdOQ2FWKEHXaxRz6KNw2w5tX/pJ+g0odVyMPQKZ6JOczukrv3Tl6kcL99ROgVwg24
Oo7qIDk1kyCNBbC54daoy43Y+S1delSZr4mNlEO5G1/PkRk5GQd43f1i45qHUrV317hqnTGjNqMKqDfZbEt6AzIcI5vXJ0BoVdcA1lEE2LSoiAnpfP0ul4SA0apRDOoFAZ8zkrhWeA/UoYdSFGiJa/JS/+OUa03rlkb9UJ7pzyuYiseRypS1OHLpxN8cu4cWkG3Qi
Q7FXx+wmqYNTTZidpKG5rtkd7BJr4GxkxhXmk+GdjcLbtg5vHWsdjjOBaHUxPSTPVWMu9yNZFUBwnO2iqtxNfTaZnKEGzdLEaoq9IE0oVKRnCgCMQW3MWwiz7tuRv3E1wJVdpU3X+lbbRxEAA9A37H/0/DNl+VDP5WtibOBFTNrJ9d9CwbiOViHfYECwG29gm4glS
0OS7/dRara/8o4y3hQIX/yML2/ppsr00cgiF8sE18DAyRbeN7gu7Hlh8/0qCJVcBhXdfLp/uC+Rgr2y4Y5myBkSlY7OR71Ys8RDIi8g="

branches:
  only:
    - master